// <auto-generated />
namespace SAglikBakanligi.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class urunAddCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(urunAddCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202006301036414_urunAddCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
